export const LOAD_BOOKLET = 'LOAD_BOOKLET';
export const LOAD_BOOKLET_SUCCESS = 'LOAD_BOOKLET_SUCCESS';
export const POST_BOOKLET = 'POST_BOOKLET';
export const POST_BOOKLET_SUCCESS = 'POST_BOOKLET_SUCCESS';
