export const LOAD_ITEM = 'LOAD_ITEM';
export const LOAD_ITEM_SUCCESS = 'LOAD_ITEM_SUCCESS';
export const LOAD_ALL_ITEMS_SUCCESS = 'LOAD_ALL_ITEMS_SUCCESS';
export const LOAD_PREV_ITEM_SUCCESS = 'LOAD_PREV_ITEM_SUCCESS';
export const LOAD_NEXT_ITEM_SUCCESS = 'LOAD_NEXT_ITEM_SUCCESS';
