export const LOAD_TOOL_SETTINGS_SUCCESS = 'LOAD_TOOL_SETTINGS_SUCCESS';
export const LOAD_TOOL_SETTINGS = 'LOAD_TOOL_SETTINGS';
export const POST_TOOL_SETTINGS = 'POST_TOOL_SETTINGS_SUCCESS';
export const POST_TOOL_SETTINGS_SUCCESS = 'POST_TOOL_SETTINGS_SUCCESS';
